# Generated by Django 4.2.20 on 2025-05-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
