# Generated by Django 4.2.20 on 2025-05-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
